### ISSUE TITLE
Parsing other video formats

### ISSUE THREAD

**Issue by Kinoman512** [matthewn4444/EBMLReader#1]
I need to extract subtitles from different video formats. Can I use this library for parsing not only the mkv file (avi for example may also contain subtitles). You plan to add other formats?

**Comment by matthewn4444** [comment]
I did not know avi can hold subtitles. Does it follow the EBML (Matroska) standard? If not then this project would not help you. Then I or someone else would have to write a custom parser for it (or you can use FFMPEG, though that overhead). I could write one (since my other project covers mp4 files). Do you have an example video file?  Or know what standard it uses?

**Comment by Kinoman512** [comment]
Sorry, the avi does not contain subtitles. I thought not only the mkv contain subtitles. I read about the video formats more. Thank you for the library
